"""Add phone and other user fields

Revision ID: 058d8c132797
Revises: 13172f831996
Create Date: 2025-07-29 12:40:28.091852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058d8c132797'
down_revision = '13172f831996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_donations', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_donation_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_donation_at')
        batch_op.drop_column('total_donations')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('instagram')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')
        batch_op.drop_column('twitter')
        batch_op.drop_column('website')
        batch_op.drop_column('bio')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
