"""new columns on the user

Revision ID: 13172f831996
Revises: f517aaa89540
Create Date: 2025-07-26 23:09:03.148716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13172f831996'
down_revision = 'f517aaa89540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
